---
resources:
- name: master
  type: git
  source:
    uri: ((github_uri))
    branch: master
    private_key: ((github_ssh_key))


- name: gh-release-candidate
  type: github-release
  source:
    owner: ((github_owner))
    repository: ((github_repo))
    access_token: ((github_token))
    release: false
    pre_release: true

- name: gh-release-final
  type: github-release
  source:
    owner: ((github_owner))
    repository: ((github_repo))
    access_token: ((github_token))
    release: true
    pre_release: false

- name: version
  type: semver
  source:
    driver: git
    uri: ((github_uri))
    branch: version
    file: version  
    private_key: ((github_ssh_key))
    initial_version: 0.0.0

jobs:
- name: build-rc
  serial_groups: [ version ]
  plan:
  - get: master
    trigger: true

  - task: build-artifact
    file: master/ci/tasks/build-artifact.yml

  - get: version
    params:
      pre: rc

  - put: gh-release-candidate
    params:
      name: version/version
      tag: version/version
      globs:
      - artifacts/*.tgz

  - put: version
    params:
      file: version/version

- name: promote-a-release
  serial_groups: [ version ]
  plan:
  - get: version
    passed: [ build-rc ]
    trigger: true
    params:
      bump: final

  - get: gh-release-candidate
    passed: [ build-rc ]

  - put: gh-release-final
    params:
      name: version/version
      tag: version/version
      globs:
      - gh-release-candidate/*.tgz

  - put: version
    params:
      file: version/version

- name: deploy
  serial_groups: [ version ]
  plan:
  - get: version
    passed: [ promote-a-release ]
    trigger: true
  - get: master

  - task: alert-deployment-start
    file: master/ci/tasks/alert.yml
    params:
      MESSAGE: Deployment of version %s started\n

  - task: alert-deployment-finish
    file: master/ci/tasks/alert.yml
    params:
      MESSAGE: Deployment of version %s finished\n

- name: patch
  serial_groups: [ version ]
  plan:
  - get: version
    passed: [ promote-a-release ]
    trigger: true

  - put: version
    params:
      bump: patch
